
services:
  zookeeper:
    image: bitnami/zookeeper
    restart: always
    ports:
      - "2181:2181"
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes

  kafka:
    image: bitnami/kafka
    ports:
      - "9092:9092"
    restart: always
    environment:
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_LISTENERS=PLAINTEXT://:9092
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://localhost:9092
    depends_on:
      - zookeeper

  redis:
    image: redis:latest
    container_name: redis-container
    ports:
      - "6379:6379"
    restart: always

#  elasticsearch:
#    container_name: elasticsearch
#    image: docker.elastic.co/elasticsearch/elasticsearch:8.11.1
#    environment:
#      - xpack.security.enabled=false
#      - discovery.type=single-node
#    networks:
#      - ntth
##    volumes:
##      - ./elasticsearch-data:/usr/share/elasticsearch/data
#    ports:
#      - 9200:9200
#  kibana:
#    container_name: kibana-Container
#    image: docker.elastic.co/kibana/kibana:8.11.1
#    environment:
#      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
#    networks:
#      - ntth
#    depends_on:
#      - elasticsearch
#    ports:
#      - 5602:5601
#  logstash:
#    container_name: logstash
#    image: docker.elastic.co/logstash/logstash:8.11.1
#    networks:
#      - ntth
##    volumes:
##      - ./logstash/pipeline:/usr/share/logstash/pipeline
#    environment:
#      - xpack.monitoring.enabled=false
#      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
#    ports:
#      - 5044:5044
#    depends_on:
#      - elasticsearch
#
#networks:
#  ntth:
#    driver: bridge
#
#  control-center:
#    image: confluentinc/cp-enterprise-control-center:7.7.0
#    hostname: control-center
#    container_name: control-center
#    depends_on:
#      - kafka
#    ports:
#      - "9021:9021"
#    environment:
#      CONTROL_CENTER_BOOTSTRAP_SERVERS: 'kafka:9092'
#      CONTROL_CENTER_REPLICATION_FACTOR: 1
#      CONTROL_CENTER_INTERNAL_TOPICS_PARTITIONS: 1
#      CONTROL_CENTER_MONITORING_INTERCEPTOR_TOPIC_PARTITIONS: 1
#      CONFLUENT_METRICS_TOPIC_REPLICATION: 1
#      PORT: 9021
#    restart: always
#




